services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: campfire
      POSTGRES_USER: campfire
      POSTGRES_PASSWORD: campfire
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
